package ql_phan_thuong;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.security.GeneralSecurityException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.ss.usermodel.WorkbookFactory;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PV
 */
public class TetThieuNhi extends javax.swing.JFrame {

    final String url = "jdbc:mysql://localhost/homework1_db";
    final String user = "root";
    final String password = "";
    
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public TetThieuNhi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        HoTen = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Tuoi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        GioiTinh = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        ConOng = new javax.swing.JTextField();
        DiaChi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        SoLuong = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        GiaTri = new javax.swing.JTextField();
        DanhSach = new javax.swing.JButton();
        Them = new javax.swing.JButton();
        ConBa = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        PhanQua = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        NAM = new javax.swing.JLabel();
        Nam = new javax.swing.JTextField();
        Update = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        Truong = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ql_phan_thuong/16.png"))); // NOI18N
        jLabel1.setText("Tết Thiếu Nhi");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ql_phan_thuong/line.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ql_phan_thuong/line.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Họ Tên: ");

        HoTen.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Tuổi:");

        Tuoi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Tuoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TuoiActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Giới Tính:");

        GioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ", "Khác" }));
        GioiTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GioiTinhActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Con Ông :");

        ConOng.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        DiaChi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Địa Chỉ:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Phần Quà:");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Số Lượng:");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("Giá Trị:");

        GiaTri.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        GiaTri.setText("(Đồng)");

        DanhSach.setBackground(new java.awt.Color(51, 204, 0));
        DanhSach.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        DanhSach.setForeground(new java.awt.Color(255, 255, 255));
        DanhSach.setText("Danh Sách Đã Trao Thưởng");
        DanhSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DanhSachActionPerformed(evt);
            }
        });

        Them.setBackground(new java.awt.Color(51, 204, 0));
        Them.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Them.setForeground(new java.awt.Color(255, 255, 255));
        Them.setText("Thêm");
        Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemActionPerformed(evt);
            }
        });

        ConBa.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setText("Con Bà :");

        PhanQua.setColumns(20);
        PhanQua.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        PhanQua.setRows(5);
        jScrollPane2.setViewportView(PhanQua);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Sản Phẩm được tạo bởi nhóm A+ CNPM CopyRight 2020");

        NAM.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        NAM.setText("Năm :");

        Nam.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        Update.setBackground(new java.awt.Color(51, 204, 0));
        Update.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Update.setForeground(new java.awt.Color(255, 255, 255));
        Update.setText("Update từ sheet");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setText(" Trường :");

        Truong.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Truong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TruongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel12)
                                            .addComponent(NAM)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(10, 10, 10))))
                                    .addComponent(Update)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(78, 78, 78)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Tuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(73, 73, 73)
                                        .addComponent(jLabel9)
                                        .addGap(33, 33, 33)
                                        .addComponent(GioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(ConOng, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(GiaTri, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(DiaChi, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Truong, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ConBa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(Them)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(DanhSach))
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(HoTen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                                        .addComponent(Nam, javax.swing.GroupLayout.Alignment.LEADING)))))
                        .addGap(144, 144, 144))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(NAM))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Nam, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(HoTen, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(GioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(ConOng, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(ConBa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel14)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Truong, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(GiaTri, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Them)
                    .addComponent(DanhSach)
                    .addComponent(Update))
                .addGap(26, 26, 26)
                .addComponent(jLabel13)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TuoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TuoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TuoiActionPerformed

    private void GioiTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GioiTinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GioiTinhActionPerformed

    private boolean checkExistEntity(String entity, String column, String table){
        
        try{
            con = DriverManager.getConnection(url, user, password);
            String sql = "SELECT * FROM " + table;
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while (rs.next()){
                if((rs.getString(column)).equals(entity)){
                    return true;
                }
            }
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
            
        }
        return false;
        
    }
    
    private boolean checkSK(String sk, String nam){
        try{
            con = DriverManager.getConnection(url, user, password);
            String sql = "SELECT * FROM Event WHERE Name = ? AND Year = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, sk);
            pst.setString(2, nam);
            ResultSet rs = pst.executeQuery();
            if(rs != null){
                
                return true;
            }
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
            
        }
        
        return false;
    }
    
    private void ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemActionPerformed
        if(Nam.getText().equals("")||HoTen.getText().equals("")||Tuoi.getText().equals("")||
           ConOng.getText().equals("")||ConBa.getText().equals("")||
           DiaChi.getText().equals("")||PhanQua.getText().equals("")||
           GiaTri.getText().equals("")||Truong.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane,"Vui Lòng Nhập Đầy Đủ Thông Tin !");
        }
        else{
            /*String path = "src/ql_phan_thuong/excel/TetThieuNhi.xlsx";
            try {
                FileInputStream FIS = new FileInputStream(path);
                Workbook workbook = WorkbookFactory.create(FIS);
                Sheet sheet = workbook.getSheetAt(0);
                
                Object[] bookData = {
                    HoTen.getText(),Tuoi.getText(),GioiTinh.getSelectedItem().toString(),ConOng.getText(),
                    ConBa.getText(),DiaChi.getText(),PhanQua.getText(),SoLuong.getValue(),GiaTri.getText()
                };
                int rowCount;
                if(sheet.getLastRowNum()==-1) rowCount=0;
                else rowCount=sheet.getLastRowNum()+1;
                Row row = sheet.createRow(rowCount);
                int columnCount =0;
                Cell cell = row.createCell(columnCount);
                cell.setCellValue(rowCount);
                for(Object field : bookData){
                    cell = row.createCell(++columnCount);
                    if (field instanceof String) {
                        cell.setCellValue((String) field);
                    } else if (field instanceof Integer) {
                        cell.setCellValue((Integer) field);
                    }
                }
                FIS.close();
                FileOutputStream outputStream = new FileOutputStream(path);
                workbook.write(outputStream);
                workbook.close();
                outputStream.close();
            } catch (IOException ex) {
                Logger.getLogger(MidAutumn.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(rootPane, "Đã Lưu !");*/
            try{
                con = DriverManager.getConnection(url, user, password);
                String insert = "";
                String update = "";
                
                if(!(checkSK("Tết thiếu nhi", Nam.getText().trim()))){
                    
                    insert = "INSERT INTO Event(`Name`, `Year`) VALUES (?, ?)";
                    pst = con.prepareStatement(insert);
                    pst.setString(1, "Tết thiếu nhi");
                    pst.setString(2, Nam.getText().trim());
                    pst.executeUpdate();
                    
                    insert = "INSERT INTO GIFT(`Gift_Name`, `Cost`) VALUES (?, ?)";
                    pst = con.prepareStatement(insert);
                    pst.setString(1, PhanQua.getText().trim());
                    pst.setString(2, GiaTri.getText().trim());
                    pst.executeUpdate();
                    
                    String select = "SELECT * FROM Event WHERE Event.Year = ?";
                    pst = con.prepareStatement(select);
                    pst.setString(1, Nam.getText().trim());
                    ResultSet rs = pst.executeQuery();
                    
                    insert = "INSERT INTO Family(`Father`, `Mother`, `Address`, `ID_E`)"
                            + "VALUES (?, ?, ?, ?)";
                    pst = con.prepareStatement(insert);
                    pst.setString(1, ConOng.getText().trim());
                    pst.setString(2, ConBa.getText().trim());
                    pst.setString(3, DiaChi.getText().trim());
                    while(rs.next()){
                        int idEv = rs.getInt("ID");
                        pst.setString(4, Integer.toString(idEv));
                    }
                    pst.executeUpdate();
                    
                    insert = "INSERT INTO Achievement(`Achievement_Name`) VALUES (?)";
                    pst = con.prepareStatement(insert);
                    pst.setString(1, "Dịp đặc biệt");
                    pst.executeUpdate();
                    
                    insert = "INSERT INTO Recipient(`Name`, `Age`, `Sex`, `School`, `ID_Family`) "
                            + "VALUES (?, ?, ?, ?, ?)";
                    String sex = GioiTinh.getSelectedItem().toString().trim();
                    pst = con.prepareStatement(insert);
                    pst.setString(1, HoTen.getText().trim());
                    pst.setString(2, Tuoi.getText().trim());
                    pst.setString(3, sex);
                    pst.setString(4, Truong.getText().trim());
                    // select id_family to insert
                    String sel = "SELECT * FROM Family "
                            + "WHERE Father like ? AND Mother like ?";
                    PreparedStatement pst2 = con.prepareStatement(sel);
                    pst2.setString(1, ConOng.getText().trim());
                    pst2.setString(2, ConBa.getText().trim());
                    ResultSet idRes = pst2.executeQuery();
                    while(idRes.next()){
                        int idFamily = idRes.getInt("ID");
                        pst.setString(5, Integer.toString(idFamily));
                    }
                    pst.executeUpdate();
                    
                    // add row to Receive_Gift table
                    // get id of recipient
                    String selectID = "SELECT * FROM Recipient, Family "
                            + "WHERE Recipient.ID_Family = Family.ID";
                    pst = con.prepareStatement(selectID);
                    rs = pst.executeQuery();
                    int idRecipient = -1;
                    while (rs.next()){
                        if (rs.getString("Name").equals(HoTen.getText().trim()) 
                                && (rs.getString("Father").equals(ConOng.getText().trim())) 
                                && (rs.getString("Mother").equals(ConBa.getText().trim())) 
                                && (rs.getString("Address").equals(DiaChi.getText().trim()))){
                            idRecipient = rs.getInt("ID");
                        }
                    }
                    int idEvent = -1;
                    int idGift = -1;
                    int idAchievement = -1;
                    // get id of Gift
                    selectID = "SELECT * FROM Gift "
                            + "WHERE Gift.Gift_Name = ?";
                    pst = con.prepareStatement(selectID);
                    pst.setString(1, PhanQua.getText().trim());
                    rs = pst.executeQuery();
                    while(rs.next()){
                        idGift = rs.getInt("ID");
                    }
                    // get id of Event 
                    selectID = "SELECT * FROM Event "
                            + "WHERE Event.Name = ?";
                    pst = con.prepareStatement(selectID);
                    pst.setString(1, "Tết thiếu nhi");
                    rs = pst.executeQuery();
                    while(rs.next()){
                        idEvent = rs.getInt("ID");
                    }
                    // get id of Achievement
                    selectID = "SELECT * FROM Achievement "
                            + "WHERE Achievement.Achievement_Name = ?";
                    pst = con.prepareStatement(selectID);
                    pst.setString(1, "Dịp đặc biệt");
                    rs = pst.executeQuery();
                    while(rs.next()){
                        idAchievement = rs.getInt("ID");
                    }

                    insert = "INSERT INTO Receive_Gift"
                            + "(`ID_Recipient`, `ID_Gift`, `ID_Event`, `ID_Achievement`, `Quantity`) "
                            + "VALUES (?, ?, ?, ?, ?)";
                    pst = con.prepareStatement(insert);
                    pst.setString(1, Integer.toString(idRecipient));
                    pst.setString(2, Integer.toString(idGift));
                    pst.setString(3, Integer.toString(idEvent));
                    pst.setString(4, Integer.toString(idAchievement));
                    pst.setString(5, Integer.toString((Integer) SoLuong.getValue()));
                    pst.executeUpdate();
                    
                    JOptionPane.showMessageDialog(rootPane, "Đã Lưu !");
                }
                else{
                    
                    String sex = GioiTinh.getSelectedItem().toString().trim();
                    if(checkExistEntity(ConOng.getText().trim(), "Father", "Family")){
                        if(checkExistEntity(ConBa.getText().trim(), "Mother", "Family")){
                            if(checkExistEntity(HoTen.getText().trim(), "Name", "Recipient")){
                                
                                String selectID = "SELECT * FROM Family, Recipient, Event "
                                        +"WHERE Family.Father = ? AND Family.Mother = ? "
                                        +"AND Family.ID = Recipient.ID_Family AND Recipient.Name = ? "
                                        +"AND Family.ID_E = Event.ID AND Event.Year = ? AND Event.Name = ? ";
                                pst = con.prepareStatement(selectID);
                                pst.setString(1, ConOng.getText().trim());
                                pst.setString(2, ConBa.getText().trim());
                                pst.setString(3, HoTen.getText().trim());
                                pst.setString(4, Nam.getText().trim());
                                pst.setString(5, "Tết thiếu nhi");
                                ResultSet rs = pst.executeQuery();
                                int idEv = 0, idF = 0;
                                while(rs.next()){
                                    int idEv1 = rs.getInt("ID_E");
                                    int idRep1 = rs.getInt("ID");
                                    idEv = idEv1;
                                    idF = idRep1;
                                }
                                selectID = "SELECT * FROM Recipient WHERE Recipient.ID_Family = ? AND Recipient.Name = ?";
                                pst = con.prepareStatement(selectID);
                                pst.setString(1, Integer.toString(idF));
                                pst.setString(2, HoTen.getText().trim());
                                rs = pst.executeQuery();
                                int idRep = 0;
                                while(rs.next()){
                                    int idRep1 = rs.getInt("ID");
                                    idRep = idRep1;
                                }
                                
                                selectID = "SELECT * FROM Receive_Gift WHERE Receive_Gift.ID_Recipient = ? AND Receive_Gift.ID_Event = ?";
                                pst = con.prepareStatement(selectID);
                                pst.setString(1, Integer.toString(idRep));
                                pst.setString(2, Integer.toString(idEv));
                                rs = pst.executeQuery();
                                int idG = 0;
                                while(rs.next()){
                                    idG = rs.getInt("ID_Gift");
                                }
                                
                                update = "UPDATE Receive_Gift SET Quantity = ? WHERE ID_Recipient = ? AND ID_Event = ?";
                                pst = con.prepareStatement(update);
                                int sl = (int) SoLuong.getValue();
                                pst.setString(1, Integer.toString(sl));
                                pst.setString(2, Integer.toString(idRep));
                                pst.setString(3, Integer.toString(idEv));
                                pst.executeUpdate();
                                
                                //System.out.println("5555");
                                
                                update = "UPDATE Gift SET Gift_Name = ?, Cost = ? WHERE ID = ?";
                                pst = con.prepareStatement(update);
                                pst.setString(1, PhanQua.getText().trim());
                                pst.setString(2, GiaTri.getText().trim());
                                pst.setString(3, Integer.toString(idG));
                                pst.executeUpdate();
                                
                                update = "UPDATE Family SET Address = ? WHERE ID = ? AND ID_E = ?";
                                pst = con.prepareStatement(update);
                                pst.setString(1, DiaChi.getText().trim());
                                pst.setString(2, Integer.toString(idF));
                                pst.setString(3, Integer.toString(idEv));
                                pst.executeUpdate();
                                
                                update = "UPDATE Recipient SET Age = ?, Sex = ?, School = ? WHERE ID = ? AND ID_Family = ?";
                                pst = con.prepareStatement(update);
                                pst.setString(1, Tuoi.getText().trim());
                                pst.setString(2, sex);
                                pst.setString(3, Truong.getText().trim());
                                pst.setString(4, Integer.toString(idRep));
                                pst.setString(5, Integer.toString(idF));
                                pst.executeUpdate();
                                
                                JOptionPane.showMessageDialog(rootPane, "Đã Lưu !");
                                //System.out.println(idRep);
                                //int idEv = rs.getInt("ID_E");
                                
                            }
                            else{
                                String selectID = "SELECT * FROM Family, Event "
                                        +"WHERE Family.Father = ? AND Family.Mother = ? "
                                        +"AND Family.ID_E = Event.ID AND Event.Year = ? AND Event.Name = ? ";
                                pst = con.prepareStatement(selectID);
                                pst.setString(1, ConOng.getText().trim());
                                pst.setString(2, ConBa.getText().trim());
                                pst.setString(3, Nam.getText().trim());
                                pst.setString(4, "Tết thiếu nhi");
                                ResultSet rs = pst.executeQuery();
                                int idF = 0, idEv = 0;
                                while(rs.next()){
                                    idF = rs.getInt("ID");
                                    idEv = rs.getInt("ID_E");
                                }
                                
                                insert = "INSERT INTO GIFT(`Gift_Name`, `Cost`) VALUES (?, ?)";
                                pst = con.prepareStatement(insert);
                                pst.setString(1, PhanQua.getText().trim());
                                pst.setString(2, GiaTri.getText().trim());
                                pst.executeUpdate();
                                
                                insert = "INSERT INTO Achievement(`Achievement_Name`) VALUES (?)";
                                pst = con.prepareStatement(insert);
                                pst.setString(1, "Dịp đặc biệt");
                                pst.executeUpdate();
                                
                                insert = "INSERT INTO Recipient(`Name`, `Age`, `Sex`, `School`, `ID_Family`) "
                                        + "VALUES (?, ?, ?, ?, ?)";
                                pst = con.prepareStatement(insert);
                                pst.setString(1, HoTen.getText().trim());
                                pst.setString(2, Tuoi.getText().trim());
                                pst.setString(3, sex);
                                pst.setString(4, Truong.getText().trim());
                                pst.setString(5, Integer.toString(idF));
                                pst.executeUpdate();
                                
                                // add row to Receive_Gift table
                                // get id of recipient
                                selectID = "SELECT * FROM Recipient "
                                            + "WHERE Recipient.ID_Family = ?";
                                pst = con.prepareStatement(selectID);
                                pst.setString(1, Integer.toString(idF));
                                rs = pst.executeQuery();
                                int idRecipient = -1;
                                while (rs.next()){
                                    idRecipient = rs.getInt("ID");
                                }
                                int idEvent = idEv;
                                int idGift = -1;
                                int idAchievement = -1;
                                // get id of Gift
                                selectID = "SELECT * FROM Gift "
                                            + "WHERE Gift.Gift_Name = ?";
                                pst = con.prepareStatement(selectID);
                                pst.setString(1, PhanQua.getText().trim());
                                rs = pst.executeQuery();
                                while(rs.next()){
                                    idGift = rs.getInt("ID");
                                }
                                
                                // get id of Achievement
                                selectID = "SELECT * FROM Achievement "
                                    + "WHERE Achievement.Achievement_Name = ?";
                                pst = con.prepareStatement(selectID);
                                pst.setString(1, "Dịp đặc biệt");
                                rs = pst.executeQuery();
                                while(rs.next()){
                                    idAchievement = rs.getInt("ID");
                                }

                                insert = "INSERT INTO Receive_Gift"
                                    + "(`ID_Recipient`, `ID_Gift`, `ID_Event`, `ID_Achievement`, `Quantity`) "
                                    + "VALUES (?, ?, ?, ?, ?)";
                                pst = con.prepareStatement(insert);
                                pst.setString(1, Integer.toString(idRecipient));
                                pst.setString(2, Integer.toString(idGift));
                                pst.setString(3, Integer.toString(idEvent));
                                pst.setString(4, Integer.toString(idAchievement));
                                pst.setString(5, Integer.toString((Integer) SoLuong.getValue()));
                                pst.executeUpdate();
                    
                                JOptionPane.showMessageDialog(rootPane, "Đã Lưu !");

                            }
                        }  
                    }
                    else if(checkExistEntity(ConOng.getText().trim(), "Father", "Family") == false
                            ||checkExistEntity(ConBa.getText().trim(), "Mother", "Family") == false){
                        
                        String select = "SELECT * FROM Event WHERE Event.Name = ? AND Event.Year = ?";
                        pst = con.prepareStatement(select);
                        pst.setString(1, "Tết Thiếu Nhi");
                        pst.setString(2, Nam.getText().trim());
                        rs = pst.executeQuery();
                        int idEv = 0;
                        while(rs.next()){
                            idEv = rs.getInt("ID");
                        }
                        
                        insert = "INSERT INTO GIFT(`Gift_Name`, `Cost`) VALUES (?, ?)";
                        pst = con.prepareStatement(insert);
                        pst.setString(1, PhanQua.getText().trim());
                        pst.setString(2, GiaTri.getText().trim());
                        pst.executeUpdate();
                        
                        insert = "INSERT INTO Family(`Father`, `Mother`, `Address`, `ID_E`)"
                            + "VALUES (?, ?, ?, ?)";
                        pst = con.prepareStatement(insert);
                        pst.setString(1, ConOng.getText().trim());
                        pst.setString(2, ConBa.getText().trim());
                        pst.setString(3, DiaChi.getText().trim());
                        pst.setString(4, Integer.toString(idEv));
                        pst.executeUpdate();
                        
                        insert = "INSERT INTO Achievement(`Achievement_Name`) VALUES (?)";
                        pst = con.prepareStatement(insert);
                        pst.setString(1, "Dịp đặc biệt");
                        pst.executeUpdate();
                        
                        insert = "INSERT INTO Recipient(`Name`, `Age`, `Sex`, `School`, `ID_Family`) "
                            + "VALUES (?, ?, ?, ?, ?)";
                        pst = con.prepareStatement(insert);
                        pst.setString(1, HoTen.getText().trim());
                        pst.setString(2, Tuoi.getText().trim());
                        pst.setString(3, sex);
                        pst.setString(4, Truong.getText().trim());
                        // select id_family to insert
                        String sel = "SELECT * FROM Family "
                                + "WHERE Father like ? AND Mother like ? AND ID_E = ?";
                        PreparedStatement pst2 = con.prepareStatement(sel);
                        pst2.setString(1, ConOng.getText().trim());
                        pst2.setString(2, ConBa.getText().trim());
                        pst2.setString(3, Integer.toString(idEv));
                        ResultSet idRes = pst2.executeQuery();
                        while(idRes.next()){
                            int idFamily = idRes.getInt("ID");
                            pst.setString(5, Integer.toString(idFamily));
                        }
                        pst.executeUpdate();
                        
                        // add row to Receive_Gift table
                        // get id of recipient
                        String selectID = "SELECT * FROM Recipient, Family "
                                + "WHERE Recipient.ID_Family = Family.ID";
                        pst = con.prepareStatement(selectID);
                        rs = pst.executeQuery();
                        int idRecipient = -1;
                        while (rs.next()){
                            if (rs.getString("Name").equals(HoTen.getText().trim()) 
                                    && (rs.getString("Father").equals(ConOng.getText().trim())) 
                                    && (rs.getString("Mother").equals(ConBa.getText().trim())) 
                                    && (rs.getString("Address").equals(DiaChi.getText().trim()))){
                                idRecipient = rs.getInt("ID");
                            }
                        }
                        int idEvent = idEv;
                        int idGift = -1;
                        int idAchievement = -1;
                        // get id of Gift
                        selectID = "SELECT * FROM Gift "
                                + "WHERE Gift.Gift_Name = ?";
                        pst = con.prepareStatement(selectID);
                        pst.setString(1, PhanQua.getText().trim());
                        rs = pst.executeQuery();
                        while(rs.next()){
                            idGift = rs.getInt("ID");
                        }
                        
                        // get id of Achievement
                        selectID = "SELECT * FROM Achievement "
                              + "WHERE Achievement.Achievement_Name = ?";
                        pst = con.prepareStatement(selectID);
                        pst.setString(1, "Dịp đặc biệt");
                        rs = pst.executeQuery();
                        while(rs.next()){
                            idAchievement = rs.getInt("ID");
                        }

                        insert = "INSERT INTO Receive_Gift"
                               + "(`ID_Recipient`, `ID_Gift`, `ID_Event`, `ID_Achievement`, `Quantity`) "
                               + "VALUES (?, ?, ?, ?, ?)";
                        pst = con.prepareStatement(insert);
                        pst.setString(1, Integer.toString(idRecipient));
                        pst.setString(2, Integer.toString(idGift));
                        pst.setString(3, Integer.toString(idEvent));
                        pst.setString(4, Integer.toString(idAchievement));
                        pst.setString(5, Integer.toString((Integer) SoLuong.getValue()));
                        pst.executeUpdate();
                        
                        JOptionPane.showMessageDialog(rootPane, "Đã Lưu !");
                    }   
                }
            }
            catch(Exception ex){
    //            JOptionPane.showMessageDialog(rootPane, ex);
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_ThemActionPerformed

    private void DanhSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DanhSachActionPerformed
        /*TetThieuNhiList ttnl = new TetThieuNhiList();
        ttnl.setVisible(true);
        ttnl.setResizable(false);
        ttnl.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);*/
        DisplayDB d = new DisplayDB();
        d.setVisible(true);
        
    }//GEN-LAST:event_DanhSachActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        TetThieuNhi1 ttn = new TetThieuNhi1();
        try {
            ttn.TruyCapSheet();
            JOptionPane.showMessageDialog(rootPane, "Đã Update !");
        } catch (IOException ex) {
            Logger.getLogger(TetThieuNhi.class.getName()).log(Level.SEVERE, null, ex);
        } catch (GeneralSecurityException ex) {
            Logger.getLogger(TetThieuNhi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_UpdateActionPerformed

    private void TruongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TruongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TruongActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TetThieuNhi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TetThieuNhi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TetThieuNhi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TetThieuNhi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TetThieuNhi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ConBa;
    private javax.swing.JTextField ConOng;
    private javax.swing.JButton DanhSach;
    private javax.swing.JTextField DiaChi;
    private javax.swing.JTextField GiaTri;
    private javax.swing.JComboBox<String> GioiTinh;
    private javax.swing.JTextField HoTen;
    private javax.swing.JLabel NAM;
    private javax.swing.JTextField Nam;
    private javax.swing.JTextArea PhanQua;
    private javax.swing.JSpinner SoLuong;
    private javax.swing.JButton Them;
    private javax.swing.JTextField Truong;
    private javax.swing.JTextField Tuoi;
    private javax.swing.JButton Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
